spring.application.name=realsync-api

spring.datasource.hikari.connection-test-query=SELECT 1

# spring.datasource.url=jdbc:mysql://db-mysql-blr1-34803-do-user-17663863-0.k.db.ondigitalocean.com:25060/hisfe
# spring.datasource.username=doadmin
# spring.datasource.password=AVNS_Xtle1_LFnhgqGvwIQWl
spring.datasource.url=jdbc:mysql://194.61.31.35:3306/remindme
spring.datasource.username=test
spring.datasource.password=Uthu@Muthu12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.security.oauth2.client.registration.google.client-id=589629555190-h2gvtq0btcakckthvea04t903e2ej3oo.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
springdoc.swagger-ui.path=/swagger-ui.html


server.port=8000

# Local Storage Configuration
# storage.local.directory=/Users/mugilan/Documents/Projects/HappyInvite/Images
storage.local.directory=/Users/m0n00qb/Documents/Personnal

# DigitalOcean Spaces Configuration
# spaces.endpoint=https://blr1.digitaloceanspaces.com
# spaces.access-key-id=DO008UZREMAA9LLA26X4
# spaces.secret-access-key=1sh12MXSdDRmYH48MldlVvUbBP+1AuKGYK8H9XzCz1E
# spaces.bucket-name=aipixture

spaces.endpoint=https://gateway.storjshare.io
spaces.access-key-id=ju72bbl3uq6caqw3lozfo6w62zga
spaces.secret-access-key=jyhunjss75vkp7nrcybrbjrw4zye7kaifuefdvm6mpmgim3qzplwq
spaces.bucket-name=airemindme

# spaces.endpoint=https://s3.ap-southeast-1.wasabisys.com
# spaces.access-key-id=1T4VOXWMJ3RL71NTL7VY
# spaces.secret-access-key=mGpsv2dJNml6kvV0zeJzUMH1csgkm4Tr2Gg1i7gm
# spaces.bucket-name=aipixture

# Switch between local and cloud storage
storage.use-cloud=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mvc.static-path-pattern=/assets/**

# server.port=443
# server.ssl.key-store=classpath:static/cert/keystore.p12
# server.ssl.key-store-password=changeit
# server.ssl.key-store-type=PKCS12

# server.ssl.key-store=/root/aipixture.jks
# server.ssl.key-store-password=Uthu@Muthu12
# server.ssl.key-store-type=JKS
# server.ssl.key-alias=aipixture

spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=reachaipixture@gmail.com
spring.mail.password=dsvn elaz qdrf sduc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.smtp.ssl.trust=smtp.gmail.com

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
